// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddMetricDialog: typeof import('./src/components/addMetricDialog.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    'Button.story': typeof import('./src/components/buttons/Button.story.vue')['default']
    RemoveMetricDialog: typeof import('./src/components/removeMetricDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonLoader: typeof import('./src/components/skeletonLoader.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
